
const answersMention = [
    `Eai #author#`,
    `Bora andar de skate #author#`,
    `Tamo junto #author#`,
    `Se cheirar melhora #author#`
]

const delayedMessages = [
    `Eu vou fazer um skate que ela não vai esquecer`,
    `Do pó nois veio no pó nóis vai`,
    'eu tô sempre na área',
    'só os loco sabem',
    'skate',
    'otário eu vou te avisar',
    'mas que preguiça boa',
    'deixe estar como está',
    'ela vai voltar',
    'eu num sou senhor do tempo',
    'wooo',
    'cheirei',
    'quanto mais a gente rala mais a gente cresce',
    'eu sei que vai chover',
    'mina linda eu quero morar na sua rua',
    'mas que preguiça boa',
    'eu sou o bicho',
    '🤙🏻',
    'não é porque eu ando de maconha que eu fumo skate',
]

const musics = [
    "Só os loucos sabem",
    "Como tudo deve ser"
]

/*
const musics = ["Céu Azul",
    "Dias de Luta, Dias de Glória",
    "Só Os Loucos Sabem",
    "Pontes Indestrutíveis",
    "Lugar Ao Sol",
    "Senhor do Tempo",
    "Zóio de Lula",
    "Vícios E Virtudes",
    "Proibida Pra Mim (Grazon)",
    "Papo Reto",
    "Meu Novo Mundo",
    "Como Tudo Deve Ser",
    "Ela Vai Voltar (Todos os Defeitos de Uma Mulher Perfeita)",
    "Tamo Aí Na Atividade",
    "Lutar Pelo Que É Meu",
    "Não É Sério (part. Negra Li)",
    "Só Por Uma Noite",
    "Aquela Paz",
    "Longe de Você",
    "Be Myself",
    "Me Encontra",
    "Hoje Eu Só Procuro a Minha Paz",
    "Tudo Que Ela Gosta de Escutar",
    "O Preço",
    "Dona do Meu Pensamento",
    "O Coro Vai Comê!",
    "Eu Protesto",
    "Buscando Um Novo Rumo",
    "Uma Criança Com Seu Olhar",
    "Beco Sem Saída",
    "Quinta-Feira",
    "Não Uso Sapato",
    "Champanhe e Água Benta",
    "Não Viva Em Vão",
    "Um Dia a Gente Se Encontra",
    "Vem Ser Minha",
    "Te Levar",
    "Hoje Eu Acordei Feliz",
    "Di-SK8 Eu Vou",
    "Eu Vim de Santos, Sou Charlie Brown",
    "Puro Sangue",
    "Não Deixe o Mar Te Engolir",
    "Tudo Pro Alto",
    "Charlie Brown Jr.",
    "Cidadão Comum Refém",
    "Cheia de Vida",
    "Camisa 10 - Joga Bola Até na Chuva (Bomba Sônica)",
    "O Errado Que Deu Certo",
    "Contrastes da Vida",
    "Nada É Impossível",
    "A Mais Linda do Bar",
    "Confisco",
    "Sem Medo da Escuridão",
    "Hoje Sou Eu Que Não Mais Te Quero",
    "A Banca",
    "O Mundo Explodiu Lá Fora",
    "Quebra-Mar",
    "Abrir Seus Olhos",
    "Somos Poucos Mas Somos Loucos",
    "Gimme o Anel",
    "Hoje",
    "Homenagem Ao Santos Futebol Clube",
    "I Feel So Good Today",
    "União",
    "A Estrada",
    "Transar No Escuro",
    "Rubão o Dono do Mundo",
    "Liberdade Acima de Tudo",
    "Ritmo, Ritual e Responsa",
    "Vivendo a Vida Numa Louca Viagem",
    "Só Pra Vadiar",
    "Só Existe o Agora",
    "Tudo Mudar",
    "Sino Dourado",
    "Essa É Por Quem Ficou Pra Trás",
    "Viver Dias de Sol",
    "A Canção do Senhor da Guerra",
    "Pra Mais Tarde Fazermos a Cabeça",
    "12 + 1",
    "Tarja Preta",
    "O Universo a Nosso Favor",
    "So Far Away",
    "Inabalavelmente",
    "T.F.D.P.",
    "Pra Não Dizer Que Não Falei Das Flores",
    "A Grande Volta",
    "O Futuro É Um Labirinto Pra Quem Não Sabe o Que Quer",
    "Vou Me Embriagar de Você",
    "Cruzei Uma Doida",
    "Você Por Perto",
    "Marginal Alado",
    "Lixo e o Luxo",
    "Respeito É Pra Quem Tem",
    "Gueto do Universo",
    "Mulher de Fases",
    "Talvez a Metade do Caminho",
    "Hoje de Noite",
    "Amor Pelas Ruas",
    "Descubra o Que Há de Errado Com Você",
    "333",
    "Ouviu-se Falar",
    "Cada Cabeça Falante Tem Sua Tromba de Elefante",
    "Na Palma da Mão (O Ragga da Baixada)",
    "Só Lazer",
    "Do Jeito Que Gosto, do Jeito Que Eu Quero",
    "Você Vai de Limusine, Eu Vou de Trem",
    "Vivendo Nesse Absurdo",
    "Samba Makossa",
    "Direto e Reto Sempre",
    "Skate Vibration",
    "Cidade Grande",
    "O Penetra",
    "É Quente",
    "Os Cortes",
    "Mantenha a Dúvida",
    "Tributo Ao Frango da Malásia",
    "Ôba, Lá Vem Ela",
    "Fina Arte",
    "Samba Triste",
    "Resolve o Meu Problema Aí",
    "O Que É da Casa, É da Casa",
    "Vida de Magnata",
    "Onde Não Existe a Paz Não Existe o Amor",
    "Todos Iguais",
    "Filho de Guerreiro",
    "Comigo Ninguém Tira Onda",
    "Ninguém Entende Você",
    "Me Dê Motivos Pra Sonhar",
    "Não Fure Os Olhos da Verdade",
    "Camisa Preta",
    "Chegou Quem Faltava",
    "A União Prevalece",
    "Festa",
    "Bons Aliados",
    "Aquele Velho Carteado e Algumas Manobrinhas",
    "Muito Antes Que Você",
    "Deus Me Deu Um Dom",
    "Bocas Ordinárias, Guerrilha",
    "Sou Quem Eu Sou",
    "Somos Extremes no Esporte e na Música",
    "Sheik",
    "História Mal Escrita",
    "Falar, Falar",
    "Nua, Linda e Inigualável",
    "Malokero SK8 Board",
    "Malabarizando",
    "Uma Só Vida pra Viver, Tenho Sede Nela Eu Vou",
    "Senhor do Tempo (part.Vanessa da Mata)",
    "Casa da Praia",
    "Lombra",
    "Com A Boca Amargando",
    "De Olhos Abertos",
    "O Que Ela Gosta É de Barriga",
    "Com Minha Loucura Faço Meu Dinheiro, Com Meu Dinheiro Faço Minhas Loucuras",
    "Cheirando Cola",
    "No Passo a Passo",
    "Criando Anticorpos",
    "Baader-Meinhof Blues",
    "O Nosso Blues",
    "Paranormal",
    "Fogo Na Bomba",
    "Ralé",
    "Bahia",
    "Rock Star",
    "Fichado",
    "Curva de Hill",
    "Hoje Sou Que Não Mais Te Quero",
    "Escalas Tropicais",
    "O Lado Certo da Vida Errada",
    "Hoje (part. Marcelo Nova)",
    "O Dom, a Inteligência e a Voz",
    "Deu Entrada Pra Subir",
    "Corra Vagabundo",
    "Peso da Batida do Errado Que Deu Certo",
    "Parta a Mil",
    "Recomeçando Com Humildade",
    "Too Fast Live, Too Young Too Die",
    "Do Surf",
    "I Feel So Good Today / Uma Criança Com Seu Olhar",
    "Green Goes",
    "Lutar Pelo Que É Meu (part. Vanessa da Mata)",
    "Liberdade Pra Dentro da Cabeça",
    "Skateboard Amor Eterno",
    "Que Espécie de Vermes São Vocês?",
    "Ai, Ai, Ai (Estúdio Coca-cola)",
    "Vou Fazer de Novo (Paranormal Attack Remix)",
    "Puxa Carro",
    "Vermelho (part. Vanessa da Mata)",
    "Música (Estúdio Coca-Cola)",
    "Indicados Para o Prêmio Nobel da Paz",
    "O Que É da Casa É da Casa/ Papo Reto (Acústico MTV)",
    "Come As You Are",
    "Hei Arreia...",
    "Local",
    "My Mini Ramp",
    "Me Deixa",
    "Onde Está o Mundo Bom?",
    "Café Foundation",
    "Trocando Uma Idéia Com Deus",
    "Marcas do Que Se Foi",
    "Molengol's Groove",
    "Geração Coca-Cola",
    "Chicanos (Skate Nos Canos)",
    "Coração Satânico (part. Marcelo Nova)",
    "Santos Futebol Clube",
    "Quando Tudo Aconteceu",
    "Killing In The Name Of",
    "Depois de Uma Bela Session, Um Belo Sofá, Pizza e Grafite",
    "Together On The Sand",
    "Pra Fazer a Cabeça",
    "Revolucionar",
    "Santa Padroeira",
    "Tema Planeta Atlântida 2010",
    "Greater Returns",
    "M&M's",
    "Open Your Eyes",
    "Fundão",
    "Legendários",
    "Provedor",
    "Tudo Igual"
]
*/


module.exports = {
    answersMention,
    delayedMessages,
    musics
}